import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { LoadingProvider } from './context/LoadingContext'
import LoadingIndicator from './components/LoadingIndicator'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-zinc-400/10">
        <LoadingProvider> 
           <LoadingIndicator />
           {children}
        </LoadingProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
